### ISSUE TITLE
Can I only display the blurred image always displayed? 

### ISSUE THREAD

**Issue by ahmed-shehataa** [orlando-dev-code/compose-image-blurhash#1]
I'm asking if I can use this library to keep the blurred image displayed because I need to achieve this scenario:  

I need to display a blurred image in the background and in the front of it the real image.

**Comment by orlandev** [comment]
No, but you can use the blurhash library which allows you to extract the bitmap from a blurhash;

 implementation 'com.github.orlandev:blurhashkt:1.0.1-alpha05'

val blurhash="LEHV6nWB2yk8pyoJadR*.7kCMdnj"
val bitmap = BlurhashDecoder.decode(blurhash, 4, 3)

**Comment by ahmed-shehataa** [comment]
Thank you
